In [1]:
import numpy as np
import pandas as pd

In [7]:
vehicle=pd.read_csv('exactkm.csv')
display(vehicle)

,Vehicle_Type,Vehicle_Age,Mileage,Engine_Temp,RPM,Oil_Pressure,Fuel_Consumption,Battery_Voltage,Brake_Pressure,Tire_Pressure,Tire_Condition,Vibration_Level,Last_Service_Months,Accident_History,KM_Range_Before_Defect,Remaining_KM
0,Hatchback,10,7984,85,1144,36,19.2,12.65,27,32,Good,High,8,No,50000-80000,51193.181212
1,Sedan,5,132389,86,1660,34,14.4,11.90,34,33,Good,High,4,No,25000-50000,32870.493814
2,SUV,10,158617,101,2588,26,10.9,12.43,43,31,Moderate,Low,11,No,25000-50000,25570.518577
3,SUV,5,54477,99,2762,39,10.3,11.89,29,29,Moderate,Medium,9,Yes,50000-80000,60574.836211
4,Sedan,3,122035,102,2146,41,13.0,12.09,44,36,Good,High,12,No,10000-25000,17854.021657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,Sedan,9,50575,84,2241,41,14.3,12.38,31,30,Good,Medium,7,No,80000+,100413.996676
11996,Sedan,11,99075,103,1701,29,16.4,12.19,41,31,Moderate,Medium,5,No,25000-50000,47860.473759
11997,Hatchback,4,235129,88,1687,34,21.7,11.88,25,30,Worn,Medium,5,Yes,25000-50000,32380.453996
11998,SUV,2,112534,101,1363,30,11.5,12.66,41,32,Good,Low,12,No,50000-80000,78557.042448
11999,Sedan,11,63624,91,2509,33,17.4,12.38,41,34,Good,Low,12,No,50000-80000,79960.319594

<h1 style="font-size:30px; color=red">LETS EXPLORE THE DATASET FIRST</h1>

In [22]:
# vehicle.head()
# vehicle.tail()
# vehicle.shape
# vehicle.info()
# vehicle.describe()
vehicle.head()

,Vehicle_Type,Vehicle_Age,Mileage,Engine_Temp,RPM,Oil_Pressure,Fuel_Consumption,Battery_Voltage,Brake_Pressure,Tire_Pressure,Tire_Condition,Vibration_Level,Last_Service_Months,Accident_History,KM_Range_Before_Defect,Remaining_KM
0,Hatchback,10,7984,85,1144,36,19.2,12.65,27,32,Good,High,8,No,50000-80000,51193.181212
1,Sedan,5,132389,86,1660,34,14.4,11.90,34,33,Good,High,4,No,25000-50000,32870.493814
2,SUV,10,158617,101,2588,26,10.9,12.43,43,31,Moderate,Low,11,No,25000-50000,25570.518577
3,SUV,5,54477,99,2762,39,10.3,11.89,29,29,Moderate,Medium,9,Yes,50000-80000,60574.836211
4,Sedan,3,122035,102,2146,41,13.0,12.09,44,36,Good,High,12,No,10000-25000,17854.021657

Display Suvs

In [26]:
suvs=vehicle[vehicle['Vehicle_Type']=='SUV'].copy()
display(suvs)

,Vehicle_Type,Vehicle_Age,Mileage,Engine_Temp,RPM,Oil_Pressure,Fuel_Consumption,Battery_Voltage,Brake_Pressure,Tire_Pressure,Tire_Condition,Vibration_Level,Last_Service_Months,Accident_History,KM_Range_Before_Defect,Remaining_KM
2,SUV,10,158617,101,2588,26,10.9,12.43,43,31,Moderate,Low,11,No,25000-50000,25570.518577
3,SUV,5,54477,99,2762,39,10.3,11.89,29,29,Moderate,Medium,9,Yes,50000-80000,60574.836211
5,SUV,10,237754,101,1556,38,10.8,12.56,28,28,Good,Medium,7,Yes,50000-80000,65055.444625
6,SUV,5,220013,99,1944,33,12.1,12.35,43,35,Good,Medium,8,No,50000-80000,71690.607365
9,SUV,9,47560,97,846,37,10.5,12.01,34,29,Good,High,9,No,50000-80000,73952.129845
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11981,SUV,8,147184,91,2153,27,11.6,11.81,25,33,Good,Medium,9,No,80000+,100020.396874
11983,SUV,2,95579,106,1412,31,11.2,11.70,26,33,Good,Low,4,Yes,25000-50000,46669.069090
11985,SUV,9,233690,102,2111,38,9.4,12.15,33,30,Worn,Low,5,No,80000+,85620.159556
11989,SUV,10,235734,96,1206,30,8.3,12.48,37,29,Good,High,10,Yes,25000-50000,49500.895418
11998,SUV,2,112534,101,1363,30,11.5,12.66,41,32,Good,Low,12,No,50000-80000,78557.042448

Vehicle older than 8 years

In [ ]:
eight_years=vehicle[vehicle['Vehicle_Age']>=8].copy()
display(eight_years)

,Vehicle_Type,Vehicle_Age,Mileage,Engine_Temp,RPM,Oil_Pressure,Fuel_Consumption,Battery_Voltage,Brake_Pressure,Tire_Pressure,Tire_Condition,Vibration_Level,Last_Service_Months,Accident_History,KM_Range_Before_Defect,Remaining_KM
0,Hatchback,10,7984,85,1144,36,19.2,12.65,27,32,Good,High,8,No,50000-80000,51193.181212
2,SUV,10,158617,101,2588,26,10.9,12.43,43,31,Moderate,Low,11,No,25000-50000,25570.518577
5,SUV,10,237754,101,1556,38,10.8,12.56,28,28,Good,Medium,7,Yes,50000-80000,65055.444625
8,Sedan,9,86770,84,1528,30,12.8,11.87,32,31,Good,Low,12,No,50000-80000,73482.413729
9,SUV,9,47560,97,846,37,10.5,12.01,34,29,Good,High,9,No,50000-80000,73952.129845
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11989,SUV,10,235734,96,1206,30,8.3,12.48,37,29,Good,High,10,Yes,25000-50000,49500.895418
11993,Truck,11,205094,107,1225,35,6.6,12.07,30,35,Moderate,High,4,No,3000-10000,3621.749954
11995,Sedan,9,50575,84,2241,41,14.3,12.38,31,30,Good,Medium,7,No,80000+,100413.996676
11996,Sedan,11,99075,103,1701,29,16.4,12.19,41,31,Moderate,Medium,5,No,25000-50000,47860.473759
11999,Sedan,11,63624,91,2509,33,17.4,12.38,41,34,Good,Low,12,No,50000-80000,79960.319594

In [32]:
vehicle.loc[[0, 1, 11999]]

,Vehicle_Type,Vehicle_Age,Mileage,Engine_Temp,RPM,Oil_Pressure,Fuel_Consumption,Battery_Voltage,Brake_Pressure,Tire_Pressure,Tire_Condition,Vibration_Level,Last_Service_Months,Accident_History,KM_Range_Before_Defect,Remaining_KM
0,Hatchback,10,7984,85,1144,36,19.2,12.65,27,32,Good,High,8,No,50000-80000,51193.181212
1,Sedan,5,132389,86,1660,34,14.4,11.90,34,33,Good,High,4,No,25000-50000,32870.493814
11999,Sedan,11,63624,91,2509,33,17.4,12.38,41,34,Good,Low,12,No,50000-80000,79960.319594

In [ ]:
#lets get top 10 vehicle with the best milage

#got vehicles with best milage
top_milage=vehicle.sort_values('Mileage',ascending=False).reset_index()
# display(top_milage)

#now to get only 10 vehicles form the list
x=top_milage.head(10).copy()
# display(x)

,index,Vehicle_Type,Vehicle_Age,Mileage,Engine_Temp,RPM,Oil_Pressure,Fuel_Consumption,Battery_Voltage,Brake_Pressure,Tire_Pressure,Tire_Condition,Vibration_Level,Last_Service_Months,Accident_History,KM_Range_Before_Defect,Remaining_KM
0,3906,Truck,2,250000,115,1053,22,7.7,12.30,30,36,Worn,High,12,No,0-3000,1587.224471
1,2398,Sedan,8,249996,93,1216,27,15.8,12.73,39,35,Good,Medium,9,No,50000-80000,75932.071438
2,7526,SUV,6,249992,95,1448,38,11.8,11.73,38,31,Good,High,1,Yes,50000-80000,74087.978779
3,1239,Truck,11,249983,112,2356,27,3.5,12.28,27,33,Worn,Low,1,No,25000-50000,45996.640635
4,5121,Truck,3,249978,97,2896,20,7.4,12.47,25,28,Worn,Low,1,No,25000-50000,38224.854175
5,9499,Hatchback,7,249947,87,724,38,14.4,12.48,35,36,Good,High,11,No,25000-50000,47166.944102
6,2180,Hatchback,3,249925,83,1742,38,14.5,12.37,32,29,Moderate,High,5,No,25000-50000,29840.790314
7,2237,SUV,2,249916,99,2633,25,14.0,11.99,34,33,Moderate,Medium,5,No,50000-80000,52066.583017
8,3252,Sedan,10,249855,87,2267,37,17.4,11.80,39,31,Worn,Low,9,No,80000+,92010.349197
9,6839,Truck,8,249827,103,1848,32,7.5,12.52,40,31,Moderate,High,10,No,10000-25000,20995.290250

In [44]:
#now lets get the vehicle with second lowest battery voltage
y=vehicle.nsmallest(2,'Battery_Voltage')
display(y)
# temp=vehicle.sort_values('Battery_Voltage')
# display(temp)

,Vehicle_Type,Vehicle_Age,Mileage,Engine_Temp,RPM,Oil_Pressure,Fuel_Consumption,Battery_Voltage,Brake_Pressure,Tire_Pressure,Tire_Condition,Vibration_Level,Last_Service_Months,Accident_History,KM_Range_Before_Defect,Remaining_KM
430,Truck,4,237336,108,2445,26,8.5,11.7,44,34,Good,Low,8,No,25000-50000,38148.877341
973,Sedan,11,176071,84,2526,33,14.7,11.7,26,34,Worn,Low,3,No,50000-80000,79156.204745

In [63]:
# avg_milage = vehicle.loc[:, [ 'Mileage']].mean(numeric_only=True)
# # print(avg_milage)
# display(avg_milage)

# display(avg_milage)

# max_engine_temp=vehicle.loc[:,['Engine_Temp']].max()
# display(max_engine_temp)

median_battery_voltage=vehicle['Battery_Voltage'].median()
display(median_battery_voltage)

np.float64(12.26)

In [ ]:
# Average mileage of each vehicle type.
# avg_milage_x=vehicle.groupby('Vehicle_Type')['Mileage'].mean()
# display(avg_milage_x)

# Count vehicles by accident history.
vehicle[vehicle['Accident_History'] == 'Yes']['Accident_History'].count()
# display(Count_vehicles)

# Highest mileage in every vehicle type.
highest_milage=vehicle.groupby('Vehicle_Type')['Mileage'].max()
display(highest_milage)

Vehicle_Type
Hatchback    249947
SUV          249992
Sedan        249996
Truck        250000
Name: Mileage, dtype: int64

In [ ]:
# Most common vehicle type.
# most_common = vehicle['Vehicle_Type'].value_counts().head(1)
# display(most_common)

# Tire condition counts.
Tire_Condition=vehicle[vehicle['Tire_Condition']=='Good']['Tire_Condition'].count()
display(Tire_Condition)


# KM range counts.

np.int64(6053)