In [1]:
import pandas as pd
import pyarrow.parquet as pq
import numpy as np

In [2]:
bios=pd.read_csv("./data/bios.csv")
# print(bios.loc[(bios["height_cm"] >= 220) & (bios['born_country']=='USA')])
display(bios.loc[
    bios["name"].str.contains("",case=False, na=False)
])

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [3]:
#filtering data using query functions
bios.query("born_country=='USA'")

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145445,149168,Kristen Santos,1994-11-02,Fairfield,Connecticut,USA,United States,NaN,NaN,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN

In [4]:
coffee=pd.read_csv('./warmup-data/coffee.csv')
coffee['price']=2.99
mask = (coffee["Coffee Type"] == "Espresso") & (coffee["Day"] == "Monday")
coffee['new_price']=np.where(mask ,7.99,2.99)
coffee = coffee.drop(columns=["price"])
coffee['revenue']=coffee['Units Sold']*coffee['new_price']
coffee.rename(columns={'new_price':'price'},inplace=True)
# display(coffee)

#using apply function to make categories
#this apply fucntion takes every coloumn from the table and apply this fucntion
# bios=pd.read_csv("./data/bios.csv")
#adding to a new coloumn of date and time 
bios['born-datetime'] = pd.to_datetime(
    bios['born_date']
)
bios['height-category'] = bios['height_cm'].apply(
    lambda x: 'Short' if x < 165 else ('Average' if x < 185 else 'Tall')
)
#we can also make a cu
display(bios)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born-datetime,height-category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895-05-11,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878-04-17,Tall
...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,2002-01-30,Average
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,1999-09-20,Average
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,1998-05-08,Short
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,1899-05-19,Average
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,1913-07-15,Tall

In [5]:
#we can also make a customized function 
def categorize_weight(row):
    if row['weight_kg']<60:
        return 'Light-Weight'
    elif row['weight_kg']<75:
        return 'Fit'
    else:
        return 'Heavy-Weight'
    
bios['Weight-Category']=bios.apply(categorize_weight,axis=1)

display(bios)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born-datetime,height-category,Weight-Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12,Tall,Heavy-Weight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01,Average,Heavy-Weight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13,Average,Heavy-Weight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895-05-11,Average,Fit
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878-04-17,Tall,Heavy-Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,2002-01-30,Average,Fit
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,1999-09-20,Average,Fit
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,1998-05-08,Short,Light-Weight
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,1899-05-19,Average,Heavy-Weight
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,1913-07-15,Tall,Heavy-Weight

In [6]:
#now we will learn about how to concantenate the data

In [7]:
# bios.head()
nocs=pd.read_csv("./data/noc_regions.csv")
# display(nocs)

# Basic Merge
# pd.merge(df1, df2, on="id")

# Inner Join (default)
# pd.merge(df1, df2, on="id", how="inner")

# Left Join
# pd.merge(df1, df2, on="id", how="left")

# Right Join
# pd.merge(df1, df2, on="id", how="right")

# # Outer Join
# pd.merge(df1, df2, on="id", how="outer")

# Different column names
# pd.merge(
#     df1,
#     df2,
#     left_on="student_id",
#     right_on="id"
# )

# Duplicate column names
# pd.merge(
#     df1,
#     df2,
#     on="id",
#     suffixes=("_left", "_right")
# )

bios_new=pd.merge(bios,nocs,left_on='born_country',right_on='NOC',how='left')
display(bios_new)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,born-datetime,height-category,Weight-Category,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12,Tall,Heavy-Weight,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01,Average,Heavy-Weight,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13,Average,Heavy-Weight,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895-05-11,Average,Fit,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878-04-17,Tall,Heavy-Weight,GBR,UK,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,2002-01-30,Average,Fit,RUS,Russia,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,1999-09-20,Average,Fit,RUS,Russia,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,1998-05-08,Short,Light-Weight,RUS,Russia,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,1899-05-19,Average,Heavy-Weight,FRA,France,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,1913-07-15,Tall,Heavy-Weight,AUS,Australia,NaN

merging and concatenation

In [8]:
usa=bios[bios['born_country']=='USA']
gbr=bios[bios['born_country']=='GBR']

bios_new=pd.concat([usa,gbr])
display(bios_new)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born-datetime,height-category,Weight-Category
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,1967-07-22,Average,Fit
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,1968-09-17,Average,Fit
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN,1973-10-03,Short,Light-Weight
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20,1897-07-01,Tall,Heavy-Weight
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN,1975-01-06,Average,Fit
...,...,...,...,...,...,...,...,...,...,...,...,...,...
144811,148512,Benjamin Alexander,1983-05-08,London,England,GBR,Jamaica,NaN,NaN,NaN,1983-05-08,Tall,Heavy-Weight
144815,148517,Ashley Watson,1993-10-28,Peterborough,England,GBR,Jamaica,NaN,NaN,NaN,1993-10-28,Tall,Heavy-Weight
145005,148716,Peder Kongshaug,2001-08-13,Wimbledon,England,GBR,Norway,184.0,86.0,NaN,2001-08-13,Average,Heavy-Weight
145319,149041,Axel Brown,1992-04-02,Harrogate,England,GBR,Trinidad and Tobago,NaN,NaN,NaN,1992-04-02,Tall,Heavy-Weight
145388,149111,Jean-Luc Baker,1993-10-07,Burnley,England,GBR,United States,NaN,NaN,NaN,1993-10-07,Tall,Heavy-Weight

Now we will Learn about how to handle NULL values

In [9]:
coffee=pd.read_csv('./warmup-data/coffee.csv')
#replacing some values with nan
coffee.loc[[0,1],"Units Sold"]=np.nan
new_coffee=coffee.fillna(coffee['Units Sold'].mean())
# display(new_coffee)

#fills the estimated value if nan is between any two null values 
coffee['Units Sold']=coffee['Units Sold'].interpolate()

# Drop rows where 'Units Sold' is missing
coffee.dropna(subset=["Units Sold"], inplace=True)
# subset=["Units Sold"] -> Check NaN only in this column
# inplace=True -> Modify the original DataFrame
coffee

          Day Coffee Type  Units Sold
2     Tuesday    Espresso        30.0
3     Tuesday       Latte        20.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

Aggregating data

In [10]:
bios[bios['born_country']=='USA']['born_region'].value_counts()

born_region
California              1634
New York                 990
Illinois                 585
Massachusetts            530
Pennsylvania             530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Kentucky                  62
Tennessee                 62
Nebraska                  60
Rhode Island              56
Montana                   55
Maine                     50
South Carolina            50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

Aggregating data using group by funtion

In [11]:
# coffee

# Group rows by 'Coffee Type'
# Select the 'Units Sold' column
# Calculate the average Units Sold for each coffee type
coffee.groupby("Coffee Type")["Units Sold"].mean()

# Perform different calculations on different columns after grouping
# coffee.groupby("Coffee Type").agg({
#     "Units Sold": "sum",   # Total units sold
#     "Price": "mean"        # Average price
# })

Coffee Type
Espresso    40.0
Latte       30.0
Name: Units Sold, dtype: float64

In [12]:
pivot = coffee.pivot(columns='Coffee Type', index='Day', values='revenue')

KeyError: 'revenue'

In [ ]:
#this will first filter height then do grouping with those and then count how many are greater
bios[bios["height_cm"] > 175].groupby("born_country")['height_cm'].count()

born_country
AFG        7
AGU        1
ALB       16
ALG       75
AND        8
          ..
VIE        7
VIN        4
Vienna     1
ZAM       22
ZIM       40
Name: height_cm, Length: 210, dtype: int64

In [ ]:
bios['born_date'] = pd.to_datetime(bios['born_date'])
bios['month_born'] = bios['born_date'].dt.month
bios['year_born'] = bios['born_date'].dt.year
bios.groupby([bios['year_born'],bios['month_born']])['name'].count().reset_index().sort_values('name', ascending=False)

      year_born  month_born  name
1437     1970.0         1.0   239
1461     1972.0         1.0   229
1497     1975.0         1.0   227
1629     1986.0         1.0   227
1617     1985.0         1.0   225
...         ...         ...   ...
1877     2006.0        12.0     1
1871     2006.0         3.0     1
20       1846.0         7.0     1
21       1846.0         8.0     1
22       1846.0         9.0     1

[1885 rows x 3 columns]


Advance Functionalities

In [ ]:
coffee['price']=2.99
coffee['revenue']=coffee['Units Sold']* coffee['price']
coffee['yesterday-revenue']=coffee['revenue'].shift(1)
def check(row):
    if row['yesterday-revenue'] == 89.70:
        row['yesterday-revenue'] = 4000
    return row

coffee = coffee.apply(check, axis=1)
coffee

          Day Coffee Type  Units Sold  price  revenue  yesterday-revenue
2     Tuesday    Espresso        30.0   2.99    89.70                NaN
3     Tuesday       Latte        20.0   2.99    59.80            4000.00
4   Wednesday    Espresso        35.0   2.99   104.65              59.80
5   Wednesday       Latte        25.0   2.99    74.75             104.65
6    Thursday    Espresso        40.0   2.99   119.60              74.75
7    Thursday       Latte        30.0   2.99    89.70             119.60
8      Friday    Espresso        45.0   2.99   134.55            4000.00
9      Friday       Latte        35.0   2.99   104.65             134.55
10   Saturday    Espresso        45.0   2.99   134.55             104.65
11   Saturday       Latte        35.0   2.99   104.65             134.55
12     Sunday    Espresso        45.0   2.99   134.55             104.65
13     Sunday       Latte        35.0   2.99   104.65             134.55

In [ ]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born-datetime,height-category,Weight-Category,month_born,year_born
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12,Tall,Heavy-Weight,12.0,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01,Average,Heavy-Weight,4.0,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13,Average,Heavy-Weight,8.0,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895-05-11,Average,Fit,5.0,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878-04-17,Tall,Heavy-Weight,4.0,1878.0

In [ ]:

bios.sort_values('height_cm', ascending=False)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born-datetime,height-category,Weight-Category,month_born,year_born
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN,1980-09-12,Tall,Heavy-Weight,9.0,1980.0
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN,1964-12-19,Tall,Heavy-Weight,12.0,1964.0
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN,1952-02-24,Tall,Heavy-Weight,2.0,1952.0
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN,1975-11-01,Tall,Heavy-Weight,11.0,1975.0
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN,1987-11-18,Tall,Heavy-Weight,11.0,1987.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145490,149217,Sin Ye-Chan,1995-06-13,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN,1995-06-13,Tall,Heavy-Weight,6.0,1995.0
145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN,1989-12-05,Tall,Heavy-Weight,12.0,1989.0
145492,149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24,1927-04-24,Tall,Heavy-Weight,4.0,1927.0
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,1998-08-31,Tall,Heavy-Weight,8.0,1998.0
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,1913-07-15,Tall,Heavy-Weight,7.0,1913.0

In [ ]:
# Assign ranks to values in a column
bios['height_rank'] = bios['height_cm'].rank()

# Default:
# - Smallest value gets rank 1
# - Equal values share the average rank

# Highest value gets rank 1
bios['height_cm'].rank(ascending=False)

0             NaN
1         27597.5
2         27597.5
3         83975.0
4             NaN
           ...
145495    87188.5
145496    83975.0
145497    96305.5
145498    89274.5
145499        NaN
Name: height_cm, Length: 145500, dtype: float64

:

In [ ]:
#if we want to select a particular type of columns we can also do that thing
coffe.se